# Generated by Django 5.1.1 on 2024-09-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modamApp', '0002_delete_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100)),
                ('produit', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
